name: Build
on:
  push:
  pull_request:
  workflow_dispatch:  # Allow manual triggering

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ij: [ IC-2023.1, IC-LATEST-STABLE, IC-LATEST-EAP-SNAPSHOT ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Build and verify
        run: ./gradlew clean buildPlugin test modernizer biz-lermitage-oga-gradle-check verifyPlugin showGeneratedPlugin -PpluginLicenseType=subscription -PpluginIdeaVersion=${{ matrix.ij }} --warning-mode all

      # Upload the build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ matrix.ij }}
          path: |
            build/libs/*.jar
            build/reports/**/*.html
            build/test-results/**/*.xml
            build/*/*.log
            build/*/*.txt
            build/*.zip
            # You can add other paths as needed, depending on what files you want to capture
